var bodyConfigs = JSON.parse(`
[
  {
    "name":"default",
    "config":{
      "lengths":[
        {
          "name":"",
          "value":0
        },
        {
          "name":"neck",
          "value":18
        },
        {
          "name":"chest",
          "value":20
        },
        {
          "name":"upperarm",
          "value":28
        },
        {
          "name":"forearm",
          "value":24
        },
        {
          "name":"thighs",
          "value":36
        },
        {
          "name":"calves",
          "value":32
        }
      ],
      "junctions":[
        {
          "name":"head",
          "sizeModifier":2.5
        },
        {
          "name":"shoulders",
          "sizeModifier":1
        },
        {
          "name":"leftelbow",
          "sizeModifier":1
        },
        {
          "name":"rightelbow",
          "sizeModifier":1
        },
        {
          "name":"lefthand",
          "sizeModifier":1
        },
        {
          "name":"righthand",
          "sizeModifier":1
        },
        {
          "name":"hips",
          "sizeModifier":1
        },
        {
          "name":"leftknee",
          "sizeModifier":1
        },
        {
          "name":"rightknee",
          "sizeModifier":1
        },
        {
          "name":"leftfoot",
          "sizeModifier":1
        },
        {
          "name":"rightfoot",
          "sizeModifier":1
        }
      ],
      "drawInstructions":[
        {
          "startName":"shoulders",
          "endNames":[
            "head",
            "hips",
            "leftelbow",
            "rightelbow"
          ]
        },
        {
          "startName":"leftelbow",
          "endNames":[
            "lefthand"
          ]
        },
        {
          "startName":"rightelbow",
          "endNames":[
            "righthand"
          ]
        },
        {
          "startName":"hips",
          "endNames":[
            "leftknee",
            "rightknee"
          ]
        },
        {
          "startName":"leftknee",
          "endNames":[
            "leftfoot"
          ]
        },
        {
          "startName":"rightknee",
          "endNames":[
            "rightfoot"
          ]
        }
      ],
      "color":"black",
      "size":13,
      "roughOptions":{
        "stroke":"white",
        "strokeWidth":2,
        "roughness":0.8,
        "fill":"#3057E1",
        "fillStyle":"solid"
      }
    }
  }
]`);
var bodyConfig = LoadConfig(bodyConfigs,"default");
