var levelConfigs = JSON.parse(`[
  {
    "name":"level0",
    "config":{
      "spawn":{
        "coordinates":{
          "x":150,
          "y":45
        },
        "direction":1,
        "frontSide":"left",
        "action":"idling"
      },
      "exit":{
        "coordinates":{
          "x":450,
          "y":20
        }
      },
      "levelLimits":{
        "width":1500,
        "height":700,
        "xLeft":20,
        "xRight":20,
        "yGround":20,
        "yCeiling":20,
        "color":"black",
        "linesRoughOptions":{
          "stroke":"black",
          "strokeWidth":2,
          "bowing":0,
          "roughness":0.8
        },
        "rectRoughOptions":{
          "stroke":"transparent",
          "strokeWidth":2,
          "fillStyle":"solid",
          "fill":"black",
          "roughness":0
        }
      },
      "blocks":{
        "roughOptions":{
          "stroke":"transparent",
          "strokeWidth":0,
          "fillStyle":"solid"
        },
        "instances":[
          {
            "xLeft":20,
            "xWidth":1500,
            "yBottom":0,
            "yHeight":45,
            "color":"transparent"
          }
        ]
      },
      "climbingHolds":{
        "roughOptions":{
          "stroke":"white",
          "strokeWidth":2,
          "fillStyle":"hachure",
          "hachureAngle":40,
          "fillWeight":1,
          "roughness":0.2,
          "fill":"white"
        },
        "instances":[]
      },
      "ladders":{
        "width":80,
        "yStep":30,
        "lineWidth":5,
        "roughOptions":{
          "stroke":"white",
          "strokeWidth":2,
          "roughness":0.8
        },
        "instances":[]
      },
      "ropes":{
        "lineWidth":4,
        "roughOptions":{
          "stroke":"white",
          "strokeWidth":2,
          "roughness":0.8
        },
        "instances":[]
      },
      "hazards":{
        "spikes":{
          "color":"black",
          "lineWidth":4,
          "roughOptions":{
            "stroke":"white",
            "strokeWidth":2,
            "roughness":0.8
          },
          "instances":[]
        }
      },
      "collectibles":{
        "gears":{
          "color":"black",
          "lineWidth":2,
          "roughOptions":{
            "stroke":"white",
            "strokeWidth":2,
            "roughness":0.5
          },
          "instances":[]
        }
      },
      "assets":[
        {
          "type":"background_sky",
          "config":{
            "gradient":[
              { "position":0, "color":"hsla(222,88%,56%,1)" },
              { "position":1, "color":"hsla(195,87%,67%,1)" }
            ]
          }
        },
        {
          "type":"ground_depth_grass",
          "layer":0,
          "order":0,
          "config":{
            "startCoords":{
              "x":0,
              "y":150
            },
            "orientation":1.571,
            "depthPolygon":{
              "startScale":0.15,
              "endScale":0.8,
              "points":[
                {"distance":0,"offset":0,"length":1500},
                {"distance":100,"offset":0,"length":1500}
              ]
            },
            "backgroundGradient":[
              { "position":0, "color":"hsla(142,40%,30%,1)" },
              { "position":1, "color":"hsla(92,64%,49%,1)" }
            ],
            "grassGradient":[
              { "position":0, "color":"hsla(120,35%,35%,0.95)" },
              { "position":1, "color":"hsla(95,60%,45%,0.95)" }
            ],
            "grassVariationGradient":[
              { "position":0, "color":"hsla(10,10%,25%,0)" },
              { "position":1, "color":"hsla(30,35%,40%,0)" }
            ],
            "tuftSize":180,
            "tuftBowing":1.5,
            "tuftMaxGapVertical":12,
            "tuftMaxGapHorizontal":15,
            "leafColorVariation":"hsla(20,30%,15%,0)",
            "leafDensity":0.4,
            "leafAngle":0.7,
            "leafBowing":0.5,
            "leafMinWidth":1.5,
            "leafMaxWidth":5,
            "leafWidthRandomness":0.5,
            "leafMinHeight":6,
            "leafMaxHeight":25,
            "leafHeightRandomness":0.4
          }
        },
        {
          "type":"wall_bricks",
          "layer":0,
          "order":0,
          "config":{
            "bottomLeftCoords":{
              "x":0,
              "y":50
            },
            "height":80,
            "width":190,
            "orientation":0,
            "layerHeightMin":15,
            "layerHeightMax":20,
            "brickWidthMin":50,
            "brickWidthMax":55,
            "brickBorderRadius":3,
            "jointThickness":0.2,
            "strokeStrength":0.4,
            "strokeColor":"black",
            "roughOptions":{
              "roughness":0.6
            },
            "brickColors":[
              "#b55b37",
              "#94472a",
              "#c8613a",
              "#dd5c38",
              "#d46239"
            ],
            "jointColor":"#6f6d64",
            "brickRoughness":6
          }
        },
        {
          "type":"wall_bricks",
          "layer":0,
          "order":0,
          "config":{
            "bottomLeftCoords":{
              "x":0,
              "y":128
            },
            "height":8,
            "width":195,
            "orientation":0,
            "layerHeightMin":20,
            "layerHeightMax":20,
            "brickWidthMin":110,
            "brickWidthMax":130,
            "brickBorderRadius":0,
            "jointThickness":1.5,
            "strokeStrength":0.4,
            "strokeColor":"black",
            "roughOptions":{
              "roughness":0.4
            },
            "brickColors":[
              "#c6c5c0",
              "#c3c1bc",
              "#bfbdb8"
            ],
            "jointColor":"#ededeb",
            "brickRoughness":10
          }
        },
        {
          "type":"fence_metal_bars",
          "layer":0,
          "order":0,
          "config":{
            "bottomLeftCoords":{
              "x":0,
              "y":136
            },
            "height":150,
            "width":190,
            "orientation":0,
            "strokeStrength":0.4,
            "strokeColor":"black",
            "roughOptions":{
              "roughness":0.4
            },
            "pillarThickness":8,
            "pillarTopShape":"spear",
            "pillarTopTransition":{"x":2,"y":8},
            "pillarTopSize":{"x":30,"y":20},
            "pillarColor":"#545454",
            "barThickness":4,
            "horizontalBarThickness":4,
            "horizontalBarColor":"#545454",
            "horizontalBars":[20,130],
            "barGap":15,
            "barsBetweenPillars":10,
            "barIndexStart":0,
            "barsHeights":[5],
            "barsLengths":[130,138,144,148,150,148,144,138],
            "barsTopShapes":["ball","spike"],
            "barsTopTransitions":[{"x":2,"y":6},{"x":4,"y":0}],
            "barsTopSizes":[{"x":3,"y":0},{"x":0,"y":12}],
            "barsColors":["#545454"]
          }
        },
        {
          "type":"wall_bricks",
          "layer":0,
          "order":0,
          "config":{
            "bottomLeftCoords":{
              "x":185,
              "y":50
            },
            "height":250,
            "width":50,
            "orientation":0,
            "layerHeightMin":15,
            "layerHeightMax":20,
            "brickWidthMin":50,
            "brickWidthMax":55,
            "brickBorderRadius":3,
            "jointThickness":0.2,
            "strokeStrength":0.4,
            "strokeColor":"black",
            "roughOptions":{
              "roughness":0.6
            },
            "brickColors":[
              "#b55b37",
              "#94472a",
              "#c8613a",
              "#dd5c38",
              "#d46239"
            ],
            "jointColor":"#6f6d64",
            "brickRoughness":6
          }
        },
        {
          "type":"wall_bricks",
          "layer":0,
          "order":0,
          "config":{
            "bottomLeftCoords":{
              "x":180,
              "y":298
            },
            "height":8,
            "width":60,
            "orientation":0,
            "layerHeightMin":20,
            "layerHeightMax":20,
            "brickWidthMin":110,
            "brickWidthMax":130,
            "brickBorderRadius":0,
            "jointThickness":1.5,
            "strokeStrength":0.4,
            "strokeColor":"black",
            "roughOptions":{
              "roughness":0.4
            },
            "brickColors":[
              "#c6c5c0",
              "#c3c1bc",
              "#bfbdb8"
            ],
            "jointColor":"#ededeb",
            "brickRoughness":10
          }
        },
        {
          "type":"fence_metal_grid",
          "layer":0,
          "order":0,
          "config":{
            "bottomLeftCoords":{
              "x":238,
              "y":50
            },
            "height":200,
            "width":420,
            "orientation":0,
            "strokeStrength":0.35,
            "strokeColor":"black",
            "roughOptions":{
              "roughness":0.4
            },
            "pillarThickness":5,
            "pillarColor":"silver",
            "pillarGap":77,
            "horizontalBarThickness":5,
            "horizontalBarColor":"silver",
            "horizontalBars":[95],
            "horizontalStrings":[10,195],
            "stringThickness":1,
            "gridColor":"silver",
            "gridGap":8
          }
        },
        {
          "type":"fence_wood_vertical",
          "layer":0,
          "order":0,
          "config":{
            "bottomLeftCoords":{
              "x":1020,
              "y":50
            },
            "height":84,
            "width":480,
            "orientation":0,
            "strokeStrength":0.4,
            "strokeColor":"black",
            "roughOptions":{
              "roughness":0.4
            },
            "pillarThickness":8,
            "pillarTopShape":"spear",
            "pillarTopTransition":{"x":2,"y":8},
            "pillarTopSize":{"x":30,"y":20},
            "pillarColor":"#523c21",
            "barThickness":15,
            "horizontalBarThickness":4,
            "horizontalBarColor":"#523c21",
            "horizontalBars":[10,70],
            "barGap":1.5,
            "barsBetweenPillars":10,
            "barIndexStart":0,
            "barsHeights":[2],
            "barsLengths":[80],
            "barsTopShapes":["spike"],
            "barsTopTransitions":[{"x":15,"y":0}],
            "barsTopSizes":[{"x":8,"y":8}],
            "barsColors":["#523c21"],
            "woodRoughness":4
          }
        },
        {
          "type":"ground_depth_concrete",
          "layer":0,
          "order":0,
          "config":{
            "startCoords":{
              "x":0,
              "y":50
            },
            "orientation":1.571,
            "depthPolygon":{
              "startScale":0.1,
              "endScale":0.8,
              "points":[
                {"distance":0,"offset":0,"length":1500},
                {"distance":50,"offset":0,"length":1500}
              ]
            },
            "backgroundGradient":[
              { "position":0, "color":"hsla(197,1%,38%,1)" },
              { "position":1, "color":"hsla(197,1%,31%,1)" }
            ],
            "strokeColor":"hsla(0,0%,50%,1)",
            "strokeMaxGapVertical":6,
            "strokeMaxGapHorizontal":50,
            "strokeMinWidth":1,
            "strokeMaxWidth":5,
            "strokeWidthRandomness":0.8
          }
        }
      ],
      "background":{
        "color":"white",
        "roughOptions":[
          {
            "stroke":"transparent",
            "fillStyle":"solid",
            "fill":"#3057E1"
          },
          {
            "stroke":"transparent",
            "strokeWidth":2,
            "roughness":0,
            "fillStyle":"cross-hatch",
            "fillWeight":0.5,
            "hachureAngle":0,
            "hachureGap":200,
            "fill":"white"
          },
          {
            "stroke":"transparent",
            "strokeWidth":2,
            "roughness":0,
            "fillStyle":"cross-hatch",
            "fillWeight":0.2,
            "hachureAngle":0,
            "hachureGap":40,
            "fill":"white"
          }
        ]
      }
    }
  },
  {
    "name":"level1",
    "config":{
      "spawn":{
        "coordinates":{
          "x":300,
          "y":20
        },
        "direction":1,
        "frontSide":"left",
        "action":"idling"
      },
      "exit":{
        "coordinates":{
          "x":2400,
          "y":20
        }
      },
      "levelLimits":{
        "width":2550,
        "height":1600,
        "xLeft":20,
        "xRight":20,
        "yGround":20,
        "yCeiling":20,
        "color":"black",
        "linesRoughOptions":{
          "stroke":"white",
          "strokeWidth":2,
          "bowing":0,
          "roughness":0.8
        },
        "rectRoughOptions":{
          "stroke":"transparent",
          "strokeWidth":2,
          "bowing":0,
          "fillStyle":"cross-hatch",
          "hachureAngle":40,
          "fillWeight":1,
          "roughness":0.8,
          "fill":"white"
        }
      },
      "blocks":{
        "roughOptions":{
          "stroke":"white",
          "strokeWidth":2,
          "fillStyle":"hachure",
          "hachureAngle":40,
          "fillWeight":1,
          "roughness":0.8,
          "fill":"white"
        },
        "instances":[
          {
            "xLeft":400,
            "xWidth":350,
            "yBottom":1250,
            "yHeight":50,
            "color":"black"
          },
          {
            "xLeft":300,
            "xWidth":500,
            "yBottom":250,
            "yHeight":100,
            "color":"black"
          },
          {
            "xLeft":1100,
            "xWidth":400,
            "yBottom":20,
            "yHeight":220,
            "color":"black"
          },
          {
            "xLeft":1300,
            "xWidth":50,
            "yBottom":240,
            "yHeight":220,
            "color":"black"
          },
          {
            "xLeft":1500,
            "xWidth":40,
            "yBottom":480,
            "yHeight":40,
            "color":"black"
          },
          {
            "xLeft":1640,
            "xWidth":40,
            "yBottom":410,
            "yHeight":40,
            "color":"black"
          },
          {
            "xLeft":1800,
            "xWidth":300,
            "yBottom":390,
            "yHeight":40,
            "color":"black"
          },
          {
            "xLeft":1700,
            "xWidth":400,
            "yBottom":700,
            "yHeight":100,
            "color":"black"
          },
          {
            "xLeft":20,
            "xWidth":860,
            "yBottom":700,
            "yHeight":120,
            "color":"black"
          },
          {
            "xLeft":500,
            "xWidth":40,
            "yBottom":350,
            "yHeight":250,
            "color":"black"
          },
          {
            "xLeft":1700,
            "xWidth":100,
            "yBottom":1000,
            "yHeight":400,
            "color":"black"
          },
          {
            "xLeft":2100,
            "xWidth":100,
            "yBottom":20,
            "yHeight":1350,
            "color":"black"
          }
        ]
      },
      "climbingHolds":{
        "roughOptions":{
          "stroke":"white",
          "strokeWidth":2,
          "fillStyle":"hachure",
          "hachureAngle":40,
          "fillWeight":1,
          "roughness":0.2,
          "fill":"white"
        },
        "instances":[]
      },
      "ladders":{
        "width":80,
        "yStep":30,
        "lineWidth":5,
        "roughOptions":{
          "stroke":"white",
          "strokeWidth":2,
          "roughness":0.8
        },
        "instances":[
          {
            "xLeft":800,
            "yBottom":20,
            "yHeight":800,
            "color":"black"
          }
        ]
      },
      "ropes":{
        "lineWidth":4,
        "roughOptions":{
          "stroke":"white",
          "strokeWidth":2,
          "roughness":0.8
        },
        "instances":[
          {
            "anchorLeft":{
              "x":750,
              "y":1500
            },
            "anchorRight":{
              "x":1700,
              "y":1000
            },
            "color":"black"
          }
        ]
      },
      "hazards":{
        "spikes":{
          "color":"black",
          "lineWidth":4,
          "roughOptions":{
            "stroke":"white",
            "strokeWidth":2,
            "roughness":0.8
          },
          "instances":[
            {
              "xLeft":1500,
              "xWidth":600,
              "yBottom":20,
              "yHeight":80,
              "patternRepeat":15,
              "direction":"up"
            }
          ]
        }
      },
      "collectibles":{
        "gears":{
          "color":"black",
          "lineWidth":2,
          "roughOptions":{
            "stroke":"white",
            "strokeWidth":2,
            "roughness":0.5
          },
          "instances":[
            {
              "coordinates":{
                "x":450,
                "y":400
              }
            },
            {
              "coordinates":{
                "x":1600,
                "y":1000
              }
            },
            {
              "coordinates":{
                "x":1950,
                "y":900
              }
            },
            {
              "coordinates":{
                "x":450,
                "y":1350
              }
            }
          ]
        }
      },
      "assets":[],
      "background":{
        "color":"white",
        "roughOptions":[
          {
            "stroke":"transparent",
            "fillStyle":"solid",
            "fill":"#3057E1"
          },
          {
            "stroke":"transparent",
            "strokeWidth":2,
            "roughness":0,
            "fillStyle":"cross-hatch",
            "fillWeight":0.5,
            "hachureAngle":0,
            "hachureGap":200,
            "fill":"white"
          },
          {
            "stroke":"transparent",
            "strokeWidth":2,
            "roughness":0,
            "fillStyle":"cross-hatch",
            "fillWeight":0.2,
            "hachureAngle":0,
            "hachureGap":40,
            "fill":"white"
          }
        ]
      }
    }
  },
  {
    "name":"level2",
    "config":{
      "spawn":{
        "coordinates":{
          "x":300,
          "y":1120
        },
        "direction":1,
        "frontSide":"left",
        "action":"idling"
      },
      "exit":{
        "coordinates":{
          "x":450,
          "y":20
        }
      },
      "levelLimits":{
        "width":2500,
        "height":1600,
        "xLeft":20,
        "xRight":20,
        "yGround":20,
        "yCeiling":20,
        "color":"black",
        "linesRoughOptions":{
          "stroke":"white",
          "strokeWidth":2,
          "bowing":0,
          "roughness":0.8
        },
        "rectRoughOptions":{
          "stroke":"transparent",
          "strokeWidth":2,
          "bowing":0,
          "fillStyle":"cross-hatch",
          "hachureAngle":40,
          "fillWeight":1,
          "roughness":0.8,
          "fill":"white"
        }
      },
      "blocks":{
        "roughOptions":{
          "stroke":"white",
          "strokeWidth":2,
          "fillStyle":"hachure",
          "hachureAngle":40,
          "fillWeight":1,
          "roughness":0.8,
          "fill":"white"
        },
        "instances":[
          {
            "xLeft":20,
            "xWidth":400,
            "yBottom":20,
            "yHeight":1100,
            "color":"black"
          },
          {
            "xLeft":420,
            "xWidth":400,
            "yBottom":20,
            "yHeight":1000,
            "color":"black"
          },
          {
            "xLeft":820,
            "xWidth":400,
            "yBottom":20,
            "yHeight":950,
            "color":"black"
          },
          {
            "xLeft":1120,
            "xWidth":100,
            "yBottom":1050,
            "yHeight":100,
            "color":"black"
          },
          {
            "xLeft":1760,
            "xWidth":30,
            "yBottom":20,
            "yHeight":90,
            "color":"black"
          },
          {
            "xLeft":1930,
            "xWidth":30,
            "yBottom":20,
            "yHeight":150,
            "color":"black"
          },
          {
            "xLeft":2070,
            "xWidth":30,
            "yBottom":20,
            "yHeight":85,
            "color":"black"
          }
        ]
      },
      "climbingHolds":{
        "roughOptions":{
          "stroke":"white",
          "strokeWidth":2,
          "fillStyle":"hachure",
          "hachureAngle":40,
          "fillWeight":1,
          "roughness":0.2,
          "fill":"white"
        },
        "instances":[
          {
            "coordinates":{
              "x":420,
              "y":1350
            },
            "size":30,
            "type":"pole",
            "hangWithLegs":false,
            "color":"black"
          },{
            "coordinates":{
              "x":1220,
              "y":600
            },
            "size":30,
            "type":"sideLeft",
            "hangWithLegs":true,
            "color":"black"
          },
          {
            "coordinates":{
              "x":1220,
              "y":830
            },
            "size":30,
            "type":"sideLeft",
            "hangWithLegs":true,
            "color":"black"
          },
          {
            "coordinates":{
              "x":1220,
              "y":450
            },
            "size":30,
            "type":"sideLeft",
            "hangWithLegs":true,
            "color":"black"
          },
          {
            "coordinates":{
              "x":1220,
              "y":240
            },
            "size":30,
            "type":"sideLeft",
            "hangWithLegs":true,
            "color":"black"
          },
          {
            "coordinates":{
              "x":1400,
              "y":950
            },
            "size":30,
            "type":"front",
            "hangWithLegs":true,
            "color":"black"
          },
          {
            "coordinates":{
              "x":1420,
              "y":220
            },
            "size":30,
            "type":"front",
            "hangWithLegs":false,
            "color":"black"
          },
          {
            "coordinates":{
              "x":1600,
              "y":220
            },
            "size":30,
            "type":"front",
            "hangWithLegs":false,
            "color":"black"
          },
          {
            "coordinates":{
              "x":1650,
              "y":360
            },
            "size":30,
            "type":"front",
            "hangWithLegs":false,
            "color":"black"
          },
          {
            "coordinates":{
              "x":2290,
              "y":360
            },
            "size":30,
            "type":"front",
            "hangWithLegs":true,
            "color":"black"
          },
          {
            "coordinates":{
              "x":2230,
              "y":250
            },
            "size":30,
            "type":"front",
            "hangWithLegs":false,
            "color":"black"
          },
          {
            "coordinates":{
              "x":2370,
              "y":275
            },
            "size":30,
            "type":"front",
            "hangWithLegs":true,
            "color":"black"
          },
          {
            "coordinates":{
              "x":2520,
              "y":295
            },
            "size":30,
            "type":"sideRight",
            "hangWithLegs":true,
            "color":"black"
          }
        ]
      },
      "ladders":{
        "width":80,
        "yStep":30,
        "lineWidth":5,
        "roughOptions":{
          "stroke":"white",
          "strokeWidth":2,
          "roughness":0.8
        },
        "instances":[]
      },
      "ropes":{
        "lineWidth":4,
        "roughOptions":{
          "stroke":"white",
          "strokeWidth":2,
          "roughness":0.8
        },
        "instances":[]
      },
      "hazards":{
        "spikes":{
          "color":"black",
          "lineWidth":4,
          "roughOptions":{
            "stroke":"white",
            "strokeWidth":2,
            "roughness":0.8
          },
          "instances":[]
        }
      },
      "collectibles":{
        "gears":{
          "color":"black",
          "lineWidth":2,
          "roughOptions":{
            "stroke":"white",
            "strokeWidth":2,
            "roughness":0.5
          },
          "instances":[]
        }
      },
      "assets":[],
      "background":{
        "color":"white",
        "roughOptions":[
          {
            "stroke":"transparent",
            "fillStyle":"solid",
            "fill":"#3057E1"
          },
          {
            "stroke":"transparent",
            "strokeWidth":2,
            "roughness":0,
            "fillStyle":"cross-hatch",
            "fillWeight":0.5,
            "hachureAngle":0,
            "hachureGap":200,
            "fill":"white"
          },
          {
            "stroke":"transparent",
            "strokeWidth":2,
            "roughness":0,
            "fillStyle":"cross-hatch",
            "fillWeight":0.2,
            "hachureAngle":0,
            "hachureGap":40,
            "fill":"white"
          }
        ]
      }
    }
  }
]`);
var levelConfig = LoadConfig(levelConfigs,"level1");
