var levelConfigs = JSON.parse(`[
  {
    "name":"level0",
    "config":{
      "spawn":{
        "coordinates":{
          "x":150,
          "y":20
        },
        "direction":1,
        "frontSide":"left",
        "action":"idling"
      },
      "exit":{
        "coordinates":{
          "x":450,
          "y":20
        }
      },
      "levelLimits":{
        "width":600,
        "height":400,
        "xLeft":20,
        "xRight":20,
        "yGround":20,
        "yCeiling":20,
        "color":"black",
        "linesRoughOptions":{
          "stroke":"white",
          "strokeWidth":2,
          "bowing":0,
          "roughness":0.8
        },
        "rectRoughOptions":{
          "stroke":"transparent",
          "strokeWidth":2,
          "bowing":0,
          "fillStyle":"cross-hatch",
          "hachureAngle":40,
          "fillWeight":1,
          "roughness":0.8,
          "fill":"white"
        }
      },
      "blocks":{
        "roughOptions":{
          "stroke":"white",
          "strokeWidth":2,
          "fillStyle":"hachure",
          "hachureAngle":40,
          "fillWeight":1,
          "roughness":0.8,
          "fill":"white"
        },
        "instances":[]
      },
      "climbingHolds":{
        "roughOptions":{
          "stroke":"white",
          "strokeWidth":2,
          "fillStyle":"hachure",
          "hachureAngle":40,
          "fillWeight":1,
          "roughness":0.2,
          "fill":"white"
        },
        "instances":[]
      },
      "ladders":{
        "width":80,
        "yStep":30,
        "lineWidth":5,
        "roughOptions":{
          "stroke":"white",
          "strokeWidth":2,
          "roughness":0.8
        },
        "instances":[]
      },
      "ropes":{
        "lineWidth":4,
        "roughOptions":{
          "stroke":"white",
          "strokeWidth":2,
          "roughness":0.8
        },
        "instances":[]
      },
      "hazards":{
        "spikes":{
          "color":"black",
          "lineWidth":4,
          "roughOptions":{
            "stroke":"white",
            "strokeWidth":2,
            "roughness":0.8
          },
          "instances":[]
        }
      },
      "collectibles":{
        "gears":{
          "color":"black",
          "lineWidth":2,
          "roughOptions":{
            "stroke":"white",
            "strokeWidth":2,
            "roughness":0.5
          },
          "instances":[]
        }
      },
      "background":{
        "color":"white",
        "roughOptions":[
          {
            "stroke":"transparent",
            "fillStyle":"solid",
            "fill":"#3057E1"
          },
          {
            "stroke":"transparent",
            "strokeWidth":2,
            "roughness":0,
            "fillStyle":"cross-hatch",
            "fillWeight":0.5,
            "hachureAngle":0,
            "hachureGap":200,
            "fill":"white"
          },
          {
            "stroke":"transparent",
            "strokeWidth":2,
            "roughness":0,
            "fillStyle":"cross-hatch",
            "fillWeight":0.2,
            "hachureAngle":0,
            "hachureGap":40,
            "fill":"white"
          }
        ]
      }
    }
  },
  {
    "name":"level1",
    "config":{
      "spawn":{
        "coordinates":{
          "x":300,
          "y":20
        },
        "direction":1,
        "frontSide":"left",
        "action":"idling"
      },
      "exit":{
        "coordinates":{
          "x":2400,
          "y":20
        }
      },
      "levelLimits":{
        "width":2550,
        "height":1600,
        "xLeft":20,
        "xRight":20,
        "yGround":20,
        "yCeiling":20,
        "color":"black",
        "linesRoughOptions":{
          "stroke":"white",
          "strokeWidth":2,
          "bowing":0,
          "roughness":0.8
        },
        "rectRoughOptions":{
          "stroke":"transparent",
          "strokeWidth":2,
          "bowing":0,
          "fillStyle":"cross-hatch",
          "hachureAngle":40,
          "fillWeight":1,
          "roughness":0.8,
          "fill":"white"
        }
      },
      "blocks":{
        "roughOptions":{
          "stroke":"white",
          "strokeWidth":2,
          "fillStyle":"hachure",
          "hachureAngle":40,
          "fillWeight":1,
          "roughness":0.8,
          "fill":"white"
        },
        "instances":[
          {
            "xLeft":400,
            "xWidth":350,
            "yBottom":1250,
            "yHeight":50,
            "color":"black"
          },
          {
            "xLeft":300,
            "xWidth":500,
            "yBottom":250,
            "yHeight":100,
            "color":"black"
          },
          {
            "xLeft":1100,
            "xWidth":400,
            "yBottom":20,
            "yHeight":220,
            "color":"black"
          },
          {
            "xLeft":1300,
            "xWidth":50,
            "yBottom":240,
            "yHeight":220,
            "color":"black"
          },
          {
            "xLeft":1500,
            "xWidth":40,
            "yBottom":480,
            "yHeight":40,
            "color":"black"
          },
          {
            "xLeft":1640,
            "xWidth":40,
            "yBottom":410,
            "yHeight":40,
            "color":"black"
          },
          {
            "xLeft":1800,
            "xWidth":300,
            "yBottom":390,
            "yHeight":40,
            "color":"black"
          },
          {
            "xLeft":1700,
            "xWidth":400,
            "yBottom":700,
            "yHeight":100,
            "color":"black"
          },
          {
            "xLeft":20,
            "xWidth":860,
            "yBottom":700,
            "yHeight":120,
            "color":"black"
          },
          {
            "xLeft":500,
            "xWidth":40,
            "yBottom":350,
            "yHeight":250,
            "color":"black"
          },
          {
            "xLeft":1700,
            "xWidth":100,
            "yBottom":1000,
            "yHeight":400,
            "color":"black"
          },
          {
            "xLeft":2100,
            "xWidth":100,
            "yBottom":20,
            "yHeight":1350,
            "color":"black"
          }
        ]
      },
      "climbingHolds":{
        "roughOptions":{
          "stroke":"white",
          "strokeWidth":2,
          "fillStyle":"hachure",
          "hachureAngle":40,
          "fillWeight":1,
          "roughness":0.2,
          "fill":"white"
        },
        "instances":[]
      },
      "ladders":{
        "width":80,
        "yStep":30,
        "lineWidth":5,
        "roughOptions":{
          "stroke":"white",
          "strokeWidth":2,
          "roughness":0.8
        },
        "instances":[
          {
            "xLeft":800,
            "yBottom":20,
            "yHeight":800,
            "color":"black"
          }
        ]
      },
      "ropes":{
        "lineWidth":4,
        "roughOptions":{
          "stroke":"white",
          "strokeWidth":2,
          "roughness":0.8
        },
        "instances":[
          {
            "anchorLeft":{
              "x":750,
              "y":1500
            },
            "anchorRight":{
              "x":1700,
              "y":1000
            },
            "color":"black"
          }
        ]
      },
      "hazards":{
        "spikes":{
          "color":"black",
          "lineWidth":4,
          "roughOptions":{
            "stroke":"white",
            "strokeWidth":2,
            "roughness":0.8
          },
          "instances":[
            {
              "xLeft":1500,
              "xWidth":600,
              "yBottom":20,
              "yHeight":80,
              "patternRepeat":15,
              "direction":"up"
            }
          ]
        }
      },
      "collectibles":{
        "gears":{
          "color":"black",
          "lineWidth":2,
          "roughOptions":{
            "stroke":"white",
            "strokeWidth":2,
            "roughness":0.5
          },
          "instances":[
            {
              "coordinates":{
                "x":450,
                "y":400
              }
            },
            {
              "coordinates":{
                "x":1600,
                "y":1000
              }
            },
            {
              "coordinates":{
                "x":1950,
                "y":900
              }
            },
            {
              "coordinates":{
                "x":450,
                "y":1350
              }
            }
          ]
        }
      },
      "background":{
        "color":"white",
        "roughOptions":[
          {
            "stroke":"transparent",
            "fillStyle":"solid",
            "fill":"#3057E1"
          },
          {
            "stroke":"transparent",
            "strokeWidth":2,
            "roughness":0,
            "fillStyle":"cross-hatch",
            "fillWeight":0.5,
            "hachureAngle":0,
            "hachureGap":200,
            "fill":"white"
          },
          {
            "stroke":"transparent",
            "strokeWidth":2,
            "roughness":0,
            "fillStyle":"cross-hatch",
            "fillWeight":0.2,
            "hachureAngle":0,
            "hachureGap":40,
            "fill":"white"
          }
        ]
      }
    }
  },
  {
    "name":"level2",
    "config":{
      "spawn":{
        "coordinates":{
          "x":1450,
          "y":20
        },
        "direction":1,
        "frontSide":"left",
        "action":"idling"
      },
      "exit":{
        "coordinates":{
          "x":450,
          "y":20
        }
      },
      "levelLimits":{
        "width":2500,
        "height":1600,
        "xLeft":20,
        "xRight":20,
        "yGround":20,
        "yCeiling":20,
        "color":"black",
        "linesRoughOptions":{
          "stroke":"white",
          "strokeWidth":2,
          "bowing":0,
          "roughness":0.8
        },
        "rectRoughOptions":{
          "stroke":"transparent",
          "strokeWidth":2,
          "bowing":0,
          "fillStyle":"cross-hatch",
          "hachureAngle":40,
          "fillWeight":1,
          "roughness":0.8,
          "fill":"white"
        }
      },
      "blocks":{
        "roughOptions":{
          "stroke":"white",
          "strokeWidth":2,
          "fillStyle":"hachure",
          "hachureAngle":40,
          "fillWeight":1,
          "roughness":0.8,
          "fill":"white"
        },
        "instances":[
          {
            "xLeft":20,
            "xWidth":400,
            "yBottom":20,
            "yHeight":1100,
            "color":"black"
          },
          {
            "xLeft":420,
            "xWidth":400,
            "yBottom":20,
            "yHeight":1000,
            "color":"black"
          },
          {
            "xLeft":820,
            "xWidth":400,
            "yBottom":20,
            "yHeight":950,
            "color":"black"
          },
          {
            "xLeft":1120,
            "xWidth":100,
            "yBottom":1050,
            "yHeight":100,
            "color":"black"
          },
          {
            "xLeft":1760,
            "xWidth":30,
            "yBottom":20,
            "yHeight":90,
            "color":"black"
          },
          {
            "xLeft":1930,
            "xWidth":30,
            "yBottom":20,
            "yHeight":150,
            "color":"black"
          },
          {
            "xLeft":2070,
            "xWidth":30,
            "yBottom":20,
            "yHeight":85,
            "color":"black"
          }
        ]
      },
      "climbingHolds":{
        "roughOptions":{
          "stroke":"white",
          "strokeWidth":2,
          "fillStyle":"hachure",
          "hachureAngle":40,
          "fillWeight":1,
          "roughness":0.2,
          "fill":"white"
        },
        "instances":[
          {
            "coordinates":{
              "x":1220,
              "y":600
            },
            "size":30,
            "type":"sideLeft",
            "hangWithLegs":true,
            "color":"black"
          },
          {
            "coordinates":{
              "x":1220,
              "y":830
            },
            "size":30,
            "type":"sideLeft",
            "hangWithLegs":true,
            "color":"black"
          },
          {
            "coordinates":{
              "x":1220,
              "y":240
            },
            "size":30,
            "type":"sideLeft",
            "hangWithLegs":true,
            "color":"black"
          },
          {
            "coordinates":{
              "x":1400,
              "y":950
            },
            "size":30,
            "type":"front",
            "hangWithLegs":true,
            "color":"black"
          },
          {
            "coordinates":{
              "x":1420,
              "y":220
            },
            "size":30,
            "type":"front",
            "hangWithLegs":false,
            "color":"black"
          },
          {
            "coordinates":{
              "x":1600,
              "y":220
            },
            "size":30,
            "type":"front",
            "hangWithLegs":false,
            "color":"black"
          },
          {
            "coordinates":{
              "x":2290,
              "y":360
            },
            "size":30,
            "type":"front",
            "hangWithLegs":true,
            "color":"black"
          },
          {
            "coordinates":{
              "x":2230,
              "y":250
            },
            "size":30,
            "type":"front",
            "hangWithLegs":true,
            "color":"black"
          },
          {
            "coordinates":{
              "x":2370,
              "y":275
            },
            "size":30,
            "type":"front",
            "hangWithLegs":true,
            "color":"black"
          },
          {
            "coordinates":{
              "x":2520,
              "y":295
            },
            "size":30,
            "type":"sideRight",
            "hangWithLegs":true,
            "color":"black"
          }
        ]
      },
      "ladders":{
        "width":80,
        "yStep":30,
        "lineWidth":5,
        "roughOptions":{
          "stroke":"white",
          "strokeWidth":2,
          "roughness":0.8
        },
        "instances":[]
      },
      "ropes":{
        "lineWidth":4,
        "roughOptions":{
          "stroke":"white",
          "strokeWidth":2,
          "roughness":0.8
        },
        "instances":[]
      },
      "hazards":{
        "spikes":{
          "color":"black",
          "lineWidth":4,
          "roughOptions":{
            "stroke":"white",
            "strokeWidth":2,
            "roughness":0.8
          },
          "instances":[]
        }
      },
      "collectibles":{
        "gears":{
          "color":"black",
          "lineWidth":2,
          "roughOptions":{
            "stroke":"white",
            "strokeWidth":2,
            "roughness":0.5
          },
          "instances":[]
        }
      },
      "background":{
        "color":"white",
        "roughOptions":[
          {
            "stroke":"transparent",
            "fillStyle":"solid",
            "fill":"#3057E1"
          },
          {
            "stroke":"transparent",
            "strokeWidth":2,
            "roughness":0,
            "fillStyle":"cross-hatch",
            "fillWeight":0.5,
            "hachureAngle":0,
            "hachureGap":200,
            "fill":"white"
          },
          {
            "stroke":"transparent",
            "strokeWidth":2,
            "roughness":0,
            "fillStyle":"cross-hatch",
            "fillWeight":0.2,
            "hachureAngle":0,
            "hachureGap":40,
            "fill":"white"
          }
        ]
      }
    }
  }
]`);
var levelConfig = LoadConfig(levelConfigs,"level1");
