var movementTransitionConfigs = JSON.parse(`[
  {
    "from":"running",
    "to":"falling",
    "sideSwitch":null,
    "rotationDirections":[
      {
        "endJunction":"fronthand",
        "direction":null
      },
      {
        "endJunction":"backhand",
        "direction":null
      }
    ]
  },
  {
    "from":"running",
    "to":"idling",
    "sideSwitch":null,
    "rotationDirections":[
      {
        "endJunction":"fronthand",
        "direction":null
      },
      {
        "endJunction":"backhand",
        "direction":null
      }
    ]
  },
  {
    "from":"falling",
    "to":"idling",
    "sideSwitch":null,
    "rotationDirections":[
      {
        "endJunction":"fronthand",
        "direction":null
      },
      {
        "endJunction":"backhand",
        "direction":null
      }
    ]
  },
  {
    "from":"falling",
    "to":"edgePreventFall",
    "sideSwitch":null,
    "rotationDirections":[
      {
        "endJunction":"fronthand",
        "direction":null
      },
      {
        "endJunction":"backhand",
        "direction":null
      }
    ]
  },
  {
    "from":"ropeDownSliding",
    "to":"falling",
    "sideSwitch":null,
    "rotationDirections":[
      {
        "endJunction":"fronthand",
        "direction":-1
      },
      {
        "endJunction":"backhand",
        "direction":-1
      }
    ]
  },
  {
    "from":"ropeClimbing",
    "to":"falling",
    "sideSwitch":null,
    "rotationDirections":[
      {
        "endJunction":"fronthand",
        "direction":-1
      },
      {
        "endJunction":"backhand",
        "direction":-1
      }
    ]
  },
  {
    "from":"edgeHanging",
    "to":"falling",
    "sideSwitch":null,
    "rotationDirections":[
      {
        "endJunction":"fronthand",
        "direction":-1
      },
      {
        "endJunction":"backhand",
        "direction":-1
      }
    ]
  },
  {
    "from":"edgeHanging",
    "to":"edgeClimbing",
    "sideSwitch":null,
    "frameCount":35,
    "rotationDirections":[]
  },
  {
    "from":"wallClimbing",
    "to":"edgeHanging",
    "sideSwitch":null,
    "rotationDirections":[
      {
        "endJunction":"fronthand",
        "direction":1
      },
      {
        "endJunction":"backhand",
        "direction":1
      }
    ]
  },
  {
    "from":"edgeHangingWithLegs",
    "to":"falling",
    "sideSwitch":null,
    "rotationDirections":[
      {
        "endJunction":"fronthand",
        "direction":-1
      },
      {
        "endJunction":"backhand",
        "direction":-1
      }
    ]
  },
  {
    "from":"falling",
    "to":"edgeHangingWithLegs",
    "sideSwitch":null,
    "rotationDirections":[
      {
        "endJunction":"fronthand",
        "direction":1
      },
      {
        "endJunction":"backhand",
        "direction":1
      }
    ]
  },
  {
    "from":"wallPrepareJumping",
    "to":"wallClimbing",
    "sideSwitch":null,
    "frameCount":8,
    "rotationDirections":[]
  },
  {
    "from":"running",
    "to":"crouchSliding",
    "sideSwitch":null,
    "frameCount":20,
    "rotationDirections":[]
  },
  {
    "from":"crouchSliding",
    "to":"falling",
    "sideSwitch":null,
    "frameCount":25,
    "rotationDirections":[]
  },
  {
    "from":"oneFootBalance",
    "to":"wallClimbing",
    "sideSwitch":null,
    "rotationDirections":[
      {
        "endJunction":"fronthand",
        "direction":1
      },
      {
        "endJunction":"backhand",
        "direction":1
      }
    ]
  },
  {
    "from":"oneFootBalance",
    "to":"oneFootBalanceTurning",
    "sideSwitch":null,
    "frameCount":18,
    "rotationDirections":[]
  },
  {
    "from":"oneFootBalanceTurning",
    "to":"oneFootBalance",
    "sideSwitch":null,
    "frameCount":14,
    "rotationDirections":[]
  },
  {
    "from":"idling",
    "to":"edgeHopping",
    "sideSwitch":null,
    "frameCount":12,
    "rotationDirections":[]
  },
  {
    "from":"crouching",
    "to":"edgeHopping",
    "sideSwitch":null,
    "frameCount":10,
    "rotationDirections":[]
  },
  {
    "from":"oneFootBalance",
    "to":"edgeHopping",
    "sideSwitch":null,
    "frameCount":12,
    "rotationDirections":[]
  },
  {
    "from":"edgeClimbing",
    "to":"edgeHopping",
    "sideSwitch":null,
    "frameCount":10,
    "rotationDirections":[]
  },
  {
    "from":"edgeHopping",
    "to":"falling",
    "sideSwitch":null,
    "frameCount":12,
    "rotationDirections":[]
  },
  {
    "from":"oneFootBalance",
    "to":"hoppingForwardJumping",
    "sideSwitch":null,
    "frameCount":10,
    "rotationDirections":[]
  },
  {
    "from":"hoppingForwardLanding",
    "to":"oneFootBalance",
    "sideSwitch":null,
    "frameCount":16,
    "rotationDirections":[]
  },
  {
    "from":"hoppingForwardLanding",
    "to":"hoppingForwardJumping",
    "sideSwitch":null,
    "frameCount":16,
    "rotationDirections":[]
  },
  {
    "from":"hoppingForwardLanding",
    "to":"edgePreventFall",
    "sideSwitch":null,
    "frameCount":18,
    "rotationDirections":[
      {
        "endJunction":"fronthand",
        "direction":1
      },
      {
        "endJunction":"backhand",
        "direction":1
      }
    ]
  },
  {
    "from":"edgeHangingFrontWithLegs",
    "to":"edgeHangingFrontWithLegsReady",
    "sideSwitch":null,
    "frameCount":18,
    "rotationDirections":[
      {
        "endJunction":"fronthand",
        "direction":-1
      }
    ]
  },
  {
    "from":"edgeHangingFrontWithLegsReady",
    "to":"edgeHangingFrontWithLegs",
    "sideSwitch":true,
    "frameCount":18,
    "rotationDirections":[
      {
        "endJunction":"fronthand",
        "direction":-1
      }
    ]
  },
  {
    "from":"edgeHangingFrontWithLegsReady",
    "to":"edgeHangingFrontWithLegs",
    "sideSwitch":false,
    "frameCount":18,
    "rotationDirections":[
      {
        "endJunction":"fronthand",
        "direction":1
      }
    ]
  },
  {
    "from":"edgeHangingFrontWithLegs",
    "to":"edgeHangingFrontWithLegsSideJumping",
    "sideSwitch":false,
    "frameCount":6,
    "rotationDirections":[
      {
        "endJunction":"fronthand",
        "direction":-1
      }
    ]
  },
  {
    "from":"edgeHangingFrontWithLegs",
    "to":"edgeHangingFrontWithLegsSideJumping",
    "sideSwitch":true,
    "frameCount":6,
    "rotationDirections":[
      {
        "endJunction":"fronthand",
        "direction":1
      }
    ]
  },
  {
    "from":"edgeHangingFrontWithLegsSideJumping",
    "to":"jumping",
    "sideSwitch":null,
    "indexTo":1,
    "frameCount":16,
    "rotationDirections":[]
  },
  {
    "from":"edgeHangingFrontWithLegs",
    "to":"edgeHangingFrontWithLegsJumping",
    "sideSwitch":null,
    "frameCount":6,
    "rotationDirections":[]
  },
  {
    "from":"edgeHangingFrontWithLegsJumping",
    "to":"wallClimbingFront",
    "sideSwitch":null,
    "frameCount":16,
    "rotationDirections":[]
  },
  {
    "from":"wallClimbingFront",
    "to":"falling",
    "sideSwitch":null,
    "frameCount":18,
    "rotationDirections":[
      {
        "endJunction":"fronthand",
        "direction":-1
      }
    ]
  }
]`);
