var movementOverrideConfigs = JSON.parse(`[
  {
    "name":"prepareJump",
    "config":{
      "cycle":false,
      "switchSide":false,
      "positions":[
        {
          "elements":[
            {
              "startJunction":"shoulders",
              "middleJunction":"backelbow",
              "endJunction":"backhand",
              "startLength":"upperarm",
              "endLength":"forearm",
              "angles":{
                "xy":2.5,
                "z":1,
                "forceRotationDirection":1
              },
              "extension":0.95
            },
            {
              "startJunction":"shoulders",
              "middleJunction":"frontelbow",
              "endJunction":"fronthand",
              "startLength":"upperarm",
              "endLength":"forearm",
              "angles":{
                "xy":2.2,
                "z":1,
                "forceRotationDirection":1
              },
              "extension":0.8
            }
        	]
        }
      ]
    }
  },
  {
    "name":"jumpingForward",
    "config":{
      "cycle":false,
      "switchSide":false,
      "positions":[
        {
          "offsets":{
            "velocity":{
              "x":8,
              "y":-12
            }
          },
          "elements":[]
        }
      ]
    }
  },
  {
    "name":"oneFootBalanceJumpingForward",
    "config":{
      "cycle":false,
      "switchSide":false,
      "positions":[
        {
          "offsets":{
            "velocity":{
              "x":8,
              "y":-9
            }
          },
          "elements":[]
        }
      ]
    }
  },
  {
    "name":"edgeHangingFrontJumpingForward",
    "config":{
      "cycle":false,
      "switchSide":false,
      "positions":[
        {
          "offsets":{
            "velocity":{
              "x":6,
              "y":-12
            }
          },
          "elements":[]
        }
      ]
    }
  },
  {
    "name":"edgeHangingTurningFall",
    "config":{
      "cycle":false,
      "switchSide":false,
      "positions":[
        {
          "offsets":{
            "velocity":{
              "x":3,
              "y":0
            }
          },
          "elements":[]
        }
      ]
    }
  },
  {
    "name":"edgeHangingFrontForwardFall",
    "config":{
      "cycle":false,
      "switchSide":false,
      "positions":[
        {
          "offsets":{
            "velocity":{
              "x":3,
              "y":0
            }
          },
          "elements":[]
        }
      ]
    }
  }
]`);
var movementOverrideConfig = LoadConfig(movementOverrideConfigs,"prepareJump");
